---
- name: debugging a variable
  hosts: all
  become: true
  tasks:
  - name: print ansible_facts way1
    debug:
     var: ansible_facts["architecture"]
  - name: print ansible_facts way2
    debug:
     var: ansible_facts.architecture
  - name: print ansible_facts way3
    debug:
     var: ansible_architecture
  - name: print ip address
    debug:
     var: ansible_default_ipv4.address
  - name: print free memory available
    debug:
     var: ansible_memfree_mb
