---
- name: create user
  hosts: all
  become: true
  vars_files:
  -  users.yml
  tasks: 
  - name: create user
    user:
     name: "{{ item.name }}"
     comment: "{{ item.comment }}"
     password: "{{ item.password | password_hash('sha512') }}"
     state: present
    loop: "{{ users }}"  
