---
- name: Ensure cups is configured
  hosts: all
  become: true
  vars_files:
  - vars.yml
  tasks:
  - name: Ensure {{ svc_name }} is present
    yum:
     name: "{{ svc_name }}"
     state: present
  - name: Ensure {{ svc_name }} is running
    service:
     name: "{{ svc_name }}"
     state: started
     enabled: true
