---
- name: create user
  hosts: all
  become: true
  tasks:
  - name: Create user
    user:
     name: Vanshika
     state: present
    register: user_data

  - name: Print user_data
    debug:
     var: user_data
