---   
- name: start httpd service
  hosts: all
  become: true
  tasks:
  - name: ensure httpd is installed
    yum:
     name: httpd
     state: latest

  - name: start httpd service
    service:
     name: httpd
     state: started

